all: main

main:
	g++ -std=c++0x src/main.cpp -o bin/main -lrt -lpthread

clean:
	rm bin/main

clean:
	rm -f src/*.o
	rm -f src/*.*~ *~
	rm -f src/DeleteEvaluador.exe src/Evaluador.exe src/ingresoelemento.exe src/iniciadorMemoria.exe src/Reporte.exe src/Salida.exe